import { IconType } from "react-icons";
import {
  SiJavascript, SiTypescript, SiPython, SiReact, SiNextdotjs, SiHtml5, SiCss,
  SiChakraui, SiTailwindcss, SiReactquery, SiNodedotjs, SiExpress, SiPostgresql,
  SiMysql, SiPrisma, SiSupabase, SiRedis, SiJsonwebtokens, SiDocker, SiKubernetes,
  SiTerraform, SiGithubactions, SiCloudflare, SiRender,
  SiPandas, SiNumpy, SiScikitlearn, SiGit,
  SiGithub, SiJira, SiOpentelemetry, SiPrometheus, SiGrafana,
} from "react-icons/si";
import { FaDatabase, FaInfinity, FaChartBar } from "react-icons/fa";
import { TbApi } from "react-icons/tb";
import { DiScrum } from "react-icons/di";
import { VscAzure } from "react-icons/vsc";

export const iconMap: Record<string, { icon: IconType; color: string }> = {
  "JavaScript (ES6+)": { icon: SiJavascript, color: "#F7DF1E" },
  "TypeScript": { icon: SiTypescript, color: "#3178C6" },
  "Python": { icon: SiPython, color: "#3776AB" },
  "SQL": { icon: FaDatabase, color: "#4479A1" },
  "React.js": { icon: SiReact, color: "#61DAFB" },
  "Next.js": { icon: SiNextdotjs, color: "var(--text-primary)" },
  "React Native": { icon: SiReact, color: "#61DAFB" },
  "HTML5": { icon: SiHtml5, color: "#E34F26" },
  "CSS3": { icon: SiCss, color: "#1572B6" },
  "ChakraUI": { icon: SiChakraui, color: "#319795" },
  "Tailwind CSS": { icon: SiTailwindcss, color: "#06B6D4" },
  "TanStack Query": { icon: SiReactquery, color: "#FF4154" },
  "Node.js": { icon: SiNodedotjs, color: "#339933" },
  "Express.js": { icon: SiExpress, color: "var(--text-primary)" },
  "REST APIs": { icon: TbApi, color: "#009688" },
  "PostgreSQL": { icon: SiPostgresql, color: "#4169E1" },
  "MySQL": { icon: SiMysql, color: "#4479A1" },
  "Prisma ORM": { icon: SiPrisma, color: "var(--text-primary)" },
  "Supabase": { icon: SiSupabase, color: "#3ECF8E" },
  "Redis": { icon: SiRedis, color: "#DC382D" },
  "JWT/OAuth": { icon: SiJsonwebtokens, color: "#FB015B" },
  "Docker": { icon: SiDocker, color: "#2496ED" },
  "Kubernetes": { icon: SiKubernetes, color: "#326CE5" },
  "Terraform": { icon: SiTerraform, color: "#7B42BC" },
  "CI/CD": { icon: FaInfinity, color: "#16B9FF" },
  "GitHub Actions": { icon: SiGithubactions, color: "#2088FF" },
  "Azure": { icon: VscAzure, color: "#0078D4" },
  "Cloudflare Workers": { icon: SiCloudflare, color: "#F38020" },
  "Render": { icon: SiRender, color: "var(--text-primary)" },
  "Power BI": { icon: FaChartBar, color: "#F2C811" },
  "SQL Server": { icon: FaDatabase, color: "#CC292B" },
  "SSIS/SSAS": { icon: FaDatabase, color: "#0078D4" },
  "Pandas": { icon: SiPandas, color: "#150458" },
  "NumPy": { icon: SiNumpy, color: "#013243" },
  "Scikit-learn": { icon: SiScikitlearn, color: "#F7931E" },
  "Git": { icon: SiGit, color: "#F05032" },
  "GitHub": { icon: SiGithub, color: "var(--text-primary)" },
  "Scrum": { icon: DiScrum, color: "#0052CC" },
  "Jira": { icon: SiJira, color: "#0052CC" },
  "OpenTelemetry": { icon: SiOpentelemetry, color: "var(--text-primary)" },
  "Prometheus": { icon: SiPrometheus, color: "#E6522C" },
  "Grafana": { icon: SiGrafana, color: "#F46800" },
  // Aliases for project tags
  "React": { icon: SiReact, color: "#61DAFB" },
  "Express": { icon: SiExpress, color: "var(--text-primary)" },
  "Prisma": { icon: SiPrisma, color: "var(--text-primary)" },
  "JWT": { icon: SiJsonwebtokens, color: "#FB015B" },
  "Google OAuth": { icon: SiJsonwebtokens, color: "#FB015B" },
  "SSIS": { icon: FaDatabase, color: "#0078D4" },
  "SSAS": { icon: FaDatabase, color: "#0078D4" },
  "Docker Compose": { icon: SiDocker, color: "#2496ED" },
  "ETL": { icon: FaDatabase, color: "#4479A1" },
  "OLAP": { icon: FaDatabase, color: "#4479A1" },
  "K3d": { icon: SiKubernetes, color: "#326CE5" },
  "Tempo": { icon: SiGrafana, color: "#F46800" },
  "Expo": { icon: SiReact, color: "var(--text-primary)" },
  "Turborepo": { icon: SiReact, color: "#EF4444" },
  "Flask": { icon: SiPython, color: "var(--text-primary)" },
  "Docker Buildx": { icon: SiDocker, color: "#2496ED" },
  "Azure ACR": { icon: VscAzure, color: "#0078D4" },
  "Azure ACI": { icon: VscAzure, color: "#0078D4" },
  "Pytest": { icon: SiPython, color: "#3776AB" }
};
